Replace sigatomic_(begin|end) with disable_sigint() do ... end
JuliaIO/VideoIO.jl pull request #372
Opened 2022-07-07 15:53 UTC by mrufsvold

Based on [this issue](https://github.com/JuliaIO/VideoIO.jl/issues/371), I switched out all of the uses of sigatomic with disable_sigint. Because the functions are now wrapped in a do block, I had to define `ret` as a `Ref{Int32}` outside the block to make it accessible to the error catches. 

I tested `load()`, `get_number_frames()`, and `get_duration()` both in the REPL and using the VSCode debugger. They all worked in both cases now.

I'm not sure if there are other tests that should be run, but hopefully, someone more knowledgeable about this package and verify all is well!

2022-07-07 16:07 UTC, IanButterworth requested changes
Thanks for this.

I don't think the `Ref`'s are needed? Also the locks can be tidied up

2022-07-07 16:07 UTC, IanButterworth commented on src/avio.jl
> +        if ret[] < 0
```suggestion
        ret = disable_sigint() do
            av_read_frame(avin.format_context, avin.packet)
        end
        if ret < 0
```

2022-07-07 16:07 UTC, IanButterworth commented on src/avio.jl
> +    ret[] < 0 && error("Could not open codec")
```suggestion
    ret = disable_sigint() do
        lock(VIO_LOCK) do
            avcodec_open2(codec_context, codec, C_NULL)
        end
    end
    ret < 0 && error("Could not open codec")
```

2022-07-07 16:07 UTC, IanButterworth commented on src/encoding.jl
> +    ret[] < 0 && error("Could not open codec: Return code $(ret)")
```suggestion
    ret = disable_sigint() do
        lock(VIO_LOCK) do
            avcodec_open2(codec_context, codec, C_NULL)
        end
    end
    ret < 0 && error("Could not open codec: Return code $(ret)")
```

2022-07-07 16:07 UTC, IanButterworth commented on src/frame_graph.jl
> +        ret[] <= 0 && error("Could not scale frame")
```suggestion
        ret = disable_sigint() do
            sws_scale(
                s.sws_context,
                src_data_ptr,
                src_linesize_ptr,
                0,
                s.dstframe.height,
                dst_data_ptr,
                dst_linesize_ptr,
            )
        end
        ret <= 0 && error("Could not scale frame")
```

2022-07-07 16:07 UTC, IanButterworth commented on .gitignore
> +.vscode/
```suggestion
.vscode/

```

2022-07-07 16:29 UTC, mrufsvold commented
Addressed your feedback!

2022-07-19 04:54 UTC, IanButterworth commented on src/avio.jl
> +        # Need to declare ret outside the do block
```suggestion
```

2022-07-19 04:55 UTC, IanButterworth approved these changes
Thanks. Sorry for the delay

2022-07-19 16:09 UTC, IanButterworth commented
There seems to be a problem with nightly. Adding 1.8-nightly to evaluate.

I'll merge either way and fix on another PR

2022-07-20 03:06 UTC, merged